#!/bin/bash

C_RED='\033[0;31m'
C_GREEN='\033[0;32m'
C_YELLOW='\033[1;33m'
C_BLUE='\033[1;34m'
C_MAGENTA='\033[1;35m'
C_WHITE='\033[1;37m'
C_GRAY='\033[1;90m'
C_NO='\033[0m'

if [ -d "$1" ]; then
	printf "${C_WHITE}${1}${C_NO}/\n"
	FIND_PATH="$1"
	FIND_NAME=""
	VERBOSE=""
	DO_WRITE=""
	shift
	while [[ $# > 0 ]]; do
		if [[ "$1" =~ ^(-name|-n)$ ]]; then
			shift
			FIND_NAME="$1"
		fi
		if [[ "$1" =~ ^(-verbose|-v)$ ]]; then
			VERBOSE="1"
		fi
		if [[ "$1" =~ ^(-write|-w)$ ]]; then
			DO_WRITE="1"
		fi
		shift
	done

	TMP=$(mktemp)
	if [ "$FIND_NAME" == "" ]; then
		find "$FIND_PATH" -type f | sort >"$TMP"
	else
		find "$FIND_PATH" -type f -name "$FIND_NAME" | sort >"$TMP"
	fi

	declare -i CNT_TOTAL
	declare -i CNT_TOTAL_I
	declare -i CNT_TOTAL_V
	declare -i CNT_TOTAL_O
	declare -i CNT_CHECKED
	declare -i CNT_CHECKED_I
	declare -i CNT_CHECKED_V
	declare -i CNT_CHECKED_O
	declare -i CNT_WRONG
	CNT_TOTAL=0
	CNT_TOTAL_I=0
	CNT_TOTAL_V=0
	CNT_TOTAL_O=0
	CNT_CHECKED=0
	CNT_CHECKED_I=0
	CNT_CHECKED_V=0
	CNT_CHECKED_O=0
	CNT_WRONG=0

	while read F; do
		CNT_TOTAL="$CNT_TOTAL+1"
		FILE_NAME=$(basename -- "$F")
		FILE_EXT="${FILE_NAME##*.}"
		FILE_EXT="$(tr [A-Z] [a-z] <<<"$FILE_EXT")"
		EXIF=""
		TYPE=" "
		TYPE_STR=" "
		CTIME=$(stat -c %Y "$F")
		CTIME_YMD_HM=$(date -d @"$CTIME" +'%Y-%m-%d %H:%M')

		if [[ "$FILE_EXT" =~ ^(jpg|crw|cr2|nef|dng)$ ]]; then
			CNT_TOTAL_I="$CNT_TOTAL_I+1"
			TYPE="i"
			EXIF=$(dcraw -i -v "$F" | grep Timestamp | cut -c 12-100)
			TYPE_STR="${C_BLUE}${TYPE}${C_NO}"
		else
			if [[ "$FILE_EXT" =~ ^(mov|avi|mp4|ts|mkv)$ ]]; then
				CNT_TOTAL_V="$CNT_TOTAL_V+1"
				TYPE="v"
				EXIF=$(mediainfo --Inform="General;%Encoded_Date%" "$F" | cut -c 5-100)
				TYPE_STR="${C_YELLOW}${TYPE}${C_NO}"
			else
				CNT_TOTAL_O="$CNT_TOTAL_O+1"
			fi
		fi

		if [ "$EXIF" == "" ]; then
			CNT_CHECKED_O="$CNT_CHECKED_O+1"
			if [ "$VERBOSE" != "" ]; then
				printf "${C_GRAY}${TYPE}  ${CTIME_YMD_HM}                    ${F}${C_NO}\n"
			fi
		else
			CNT_CHECKED="$CNT_CHECKED+1"
			if [ "$TYPE" == "i" ]; then
				CNT_CHECKED_I="$CNT_CHECKED_I+1"
			fi
			if [ "$TYPE" == "v" ]; then
				CNT_CHECKED_V="$CNT_CHECKED_V+1"
			fi

			CTIME_YMD=${CTIME_YMD_HM:0:10}
			CTIME_HM=${CTIME_YMD_HM:11:5}
			EXIF_YMD_HM=$(date -d "$EXIF" +'%Y-%m-%d %H:%M') #%Y-%m-%d %H:%M.%S
			EXIF_YMD=${EXIF_YMD_HM:0:10}
			EXIF_HM=${EXIF_YMD_HM:11:5}

			if [ "$CTIME_YMD_HM" == "$EXIF_YMD_HM" ]; then #all equals
				if [ "$VERBOSE" != "" ]; then
					printf "${TYPE_STR}  ${CTIME_YMD_HM}  ${EXIF_YMD_HM}  ${F}\n"
				fi
			else
				CNT_WRONG="$CNT_WRONG+1"
				W="  "
				if [ "$DO_WRITE" != "" ]; then
					W="${C_MAGENTA}<<${C_NO}"
					touch -t $(date -d "$EXIF" +'%y%m%d%H%M.%S') "$F"
				fi
				if [ "$CTIME_YMD" == "$EXIF_YMD" ]; then #only year-month-day equals
					printf "${TYPE_STR}  ${CTIME_YMD} ${C_RED}${CTIME_HM}${C_NO}${W}${EXIF_YMD} ${C_GREEN}${EXIF_HM}${C_NO}  ${F}\n"
				else
					printf "${TYPE_STR}  ${C_RED}${CTIME_YMD_HM}${C_NO}${W}${C_GREEN}${EXIF_YMD_HM}${C_NO}  ${F}\n"
				fi
			fi
		fi
	done <"$TMP"
	rm "$TMP"

	printf "Total: "
	printf "${C_WHITE}${CNT_TOTAL}${C_NO} (${C_BLUE}${CNT_TOTAL_I}${C_NO},${C_YELLOW}${CNT_TOTAL_V}${C_NO},${C_GRAY}${CNT_TOTAL_O}${C_NO})  "
	printf "Checked: "
	printf "${C_WHITE}${CNT_CHECKED}${C_NO} (${C_BLUE}${CNT_CHECKED_I}${C_NO},${C_YELLOW}${CNT_CHECKED_V}${C_NO},${C_GRAY}${CNT_CHECKED_O}${C_NO})  "
	if [ $CNT_WRONG -eq 0 ]; then
		printf "Wrong: ${C_GREEN}${CNT_WRONG}${C_NO}\n\n"
	else
		printf "Wrong: ${C_RED}${CNT_WRONG}${C_NO}\n\n"
	fi
	exit 0
else
	SCRIPT_NAME=$(basename -- "${0}")
	echo "Use: $SCRIPT_NAME directory-to-scan [-n(ame) file-mask -v(erbose) -w(rite)]"
	exit 1
fi
